from _typeshed import AnyPath

def get_sync_directory() -> AnyPath: ...
def validate_directory(directory: AnyPath) -> bool: ...
def get_server_ip() -> tuple[str,int]: ...
def validate_ip(addr: str) -> bool: ...
def validate_port(port: str):