import socket
from _typeshed import AnyPath
import message


def main() -> None: ...
def initialize_client() -> tuple[AnyPath, socket.socket()]: ...
def find_files_to_update(directory_path: AnyPath, compared_timestamp:float) -> list[AnyPath]: ...
def send_message(sock: socket.socket, msg: message.Message()) -> None: ...
def receive_message(sock: socket.socket) -> message.Message(): ...
def prepare_command(comm: str) -> message.Message(): ...
def receive_dir_message(sock: socket.socket) -> None: ...
def convert_dir_data_to_text(data: bytes) -> str: ...
def receive_file(sock: socket.socket, f_path: AnyPath) -> None: ...
def send_file(sock:socket , absolute_path: AnyPath) -> None: ...